version: "3.8"

services:
  backend:
    image: kosolapovr/todo-app-backend
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your-secret-key
      - PORT=3000
    volumes:
      - todo-db:/app/database.db

  frontend:
    image: kosolapovr/todo-app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  todo-db:
