name: Deploy
on:
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SERVER_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SERVER_PRIVATE_KEY}} # Private or public key of the server
          username: ${{ secrets.SERVER_USERNAME }} # User of the server you want to ssh into
          script: |
            cd ./app
            git pull
            docker-compose down
            docker rmi $(docker images -q) -f || true
            docker-compose up --build -d 
            exit 0
